### ISSUE TITLE
Allow tagging of queues on creation

### ISSUE THREAD

**Issue by gregbeech** [Bogdanp/dramatiq_sqs#12]
Tagging AWS resources is really useful to keep track of which resources belong to which application, and to track things like costs on a per-application basis. Currently the SQS broker doesn't allow tags to be set on the queue, but this would be useful functionality to have.

I'm happy to contribute the PR for this if you're 👍 with it.

**Comment by Bogdanp** [comment]
That sounds like a good addition, please do contribute a PR.
